// <auto-generated />
namespace Plenamente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class actbd2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actbd2));
        
        string IMigrationMetadata.Id
        {
            get { return "201906150303196_actbd2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
